In [17]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np

from definitions import PROCESSED_DATA_DIR
from src.data.indicators import rsi, stochRSI, ema
from src.models.strategies import RSIStoch200EMA, BuyAndHold
from src.data.data_pipeline import split_timeseries

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
btcusdt = pd.read_csv(PROCESSED_DATA_DIR / 'BTCUSDT.csv')
btcusdt.index = pd.DatetimeIndex(btcusdt['open time'])

In [19]:
btcusdt

,open time,open,high,low,close,volume,ema,rsi,stoch_k,stoch_d
open time,,,,,,,,,,
2017-08-17 20:30:00,2017-08-17 20:30:00,4301.91,4354.84,4262.53,4346.74,15.184266,4346.740000,NaN,NaN,NaN
2017-08-17 21:00:00,2017-08-17 21:00:00,4346.74,4369.69,4315.85,4349.33,29.292665,4346.765771,100.000000,NaN,NaN
2017-08-17 21:30:00,2017-08-17 21:30:00,4349.33,4369.69,4309.23,4333.55,32.480371,4346.634271,13.225186,NaN,NaN
2017-08-17 22:00:00,2017-08-17 22:00:00,4333.55,4349.63,4310.00,4326.29,26.241174,4346.431840,9.248769,NaN,NaN
2017-08-17 22:30:00,2017-08-17 22:30:00,4326.29,4359.13,4319.11,4336.80,31.134968,4346.336001,38.211911,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2021-05-31 21:30:00,2021-05-31 21:30:00,36775.02,37087.30,36623.01,36932.55,840.717074,36229.710395,58.482794,0.198487,0.133164
2021-05-31 22:00:00,2021-05-31 22:00:00,36932.55,37250.00,36863.28,37090.16,1407.839699,36238.272082,61.498708,0.419132,0.235186
2021-05-31 22:30:00,2021-05-31 22:30:00,37090.16,37140.00,36835.85,36879.23,908.355699,36244.649773,55.670255,0.430699,0.349439
2021-05-31 23:00:00,2021-05-31 23:00:00,36879.23,37345.00,36800.93,37301.51,1160.566735,36255.165795,63.191393,0.580911,0.476914
2021-05-31 23:30:00,2021-05-31 23:30:00,37301.51,37499.00,37231.13,37253.81,1488.587448,36265.102554,61.913553,0.651560,0.554390

In [23]:
split_timeseries(btcusdt, 1000)

(                               open time      open      high       low  \
 open time
 2020-10-13 18:30:00  2020-10-13 18:30:00  11394.13  11394.13  11355.89
 2020-10-13 19:00:00  2020-10-13 19:00:00  11378.14  11416.12  11367.49
 2020-10-13 19:30:00  2020-10-13 19:30:00  11415.50  11435.26  11386.33
 2020-10-13 20:00:00  2020-10-13 20:00:00  11387.83  11427.75  11386.26
 2020-10-13 20:30:00  2020-10-13 20:30:00  11422.34  11429.23  11406.20
 ...                                  ...       ...       ...       ...
 2020-11-03 12:00:00  2020-11-03 12:00:00  13532.15  13550.00  13493.03
 2020-11-03 12:30:00  2020-11-03 12:30:00  13496.00  13529.02  13471.00
 2020-11-03 13:00:00  2020-11-03 13:00:00  13514.67  13669.00  13484.36
 2020-11-03 13:30:00  2020-11-03 13:30:00  13659.77  13740.78  13641.50
 2020-11-03 14:00:00  2020-11-03 14:00:00  13699.71  13732.72  13676.50

                         close       volume           ema        rsi   stoch_k  \
 open time
 2020-10-13 18:30:00  11378.13   907.333710  11320.013153  40.524758  0.490198
 2020-10-13 19:00:00  11415.50   795.622316  11320.963271  48.068238  0.766346
 2020-10-13 19:30:00  11387.83   780.755279  11321.628611  43.653312  0.783760
 2020-10-13 20:00:00  11422.45   681.874290  11322.631809  49.858630  0.920357
 2020-10-13 20:30:00  11425.01   472.118628  11323.650498  50.294540  0.920357
 ...                       ...          ...           ...        ...       ...
 2020-11-03 12:00:00  13496.00  1181.357282  13560.772027  49.469395  0.675546
 2020-11-03 12:30:00  13514.68   993.292459  13560.313400  51.661700  0.652510
 2020-11-03 13:00:00  13659.81  1958.415871  13561.303415  64.535469  0.722298
 2020-11-03 13:30:00  13699.71  3162.785829  13562.680595  67.127541  0.868820
 2020-11-03 14:00:00  13687.36  1447.702728  13563.921187  65.531006  0.973609

                       stoch_d
 open time
 2020-10-13 18:30:00  0.400869
 2020-10-13 19:00:00  0.555001
 2020-10-13 19:30:00  0.680101
 2020-10-13 20:00:00  0.823488
 2020-10-13 20:30:00  0.874825
 ...                       ...
 2020-11-03 12:00:00  0.777227
 2020-11-03 12:30:00  0.709898
 2020-11-03 13:00:00  0.683451
 2020-11-03 13:30:00  0.747876
 2020-11-03 14:00:00  0.854909

 [1000 rows x 10 columns],
                                open time      open      high       low  \
 open time
 2017-08-17 20:30:00  2017-08-17 20:30:00   4301.91   4354.84   4262.53
 2017-08-17 21:00:00  2017-08-17 21:00:00   4346.74   4369.69   4315.85
 2017-08-17 21:30:00  2017-08-17 21:30:00   4349.33   4369.69   4309.23
 2017-08-17 22:00:00  2017-08-17 22:00:00   4333.55   4349.63   4310.00
 2017-08-17 22:30:00  2017-08-17 22:30:00   4326.29   4359.13   4319.11
 ...                                  ...       ...       ...       ...
 2021-05-31 21:30:00  2021-05-31 21:30:00  36775.02  37087.30  36623.01
 2021-05-31 22:00:00  2021-05-31 22:00:00  36932.55  37250.00  36863.28
 2021-05-31 22:30:00  2021-05-31 22:30:00  37090.16  37140.00  36835.85
 2021-05-31 23:00:00  2021-05-31 23:00:00  36879.23  37345.00  36800.93
 2021-05-31 23:30:00  2021-05-31 23:30:00  37301.51  37499.00  37231.13

                         close       volume           ema         rsi  \
 open time
 2017-08-17 20:30:00   4346.74    15.184266   4346.740000         NaN
 2017-08-17 21:00:00   4349.33    29.292665   4346.765771  100.000000
 2017-08-17 21:30:00   4333.55    32.480371   4346.634271   13.225186
 2017-08-17 22:00:00   4326.29    26.241174   4346.431840    9.248769
 2017-08-17 22:30:00   4336.80    31.134968   4346.336001   38.211911
 ...                       ...          ...           ...         ...
 2021-05-31 21:30:00  36932.55   840.717074  36229.710395   58.482794
 2021-05-31 22:00:00  37090.16  1407.839699  36238.272082   61.498708
 2021-05-31 22:30:00  36879.23   908.355699  36244.649773   55.670255
 2021-05-31 23:00:00  37301.51  1160.566735  36255.165795   63.191393
 2021-05-31 23:30:00  37253.81  1488.587448  36265.102554   61.913553

                       stoch_k   stoch_d
 open time
 2017-08-17 20:30:00       NaN       NaN
 2017-08-17 21:00:00       NaN       NaN
 2017-08-17 21:30:00       NaN       NaN
 2017-08-17 22:00:00       NaN       NaN
 2017-08-17 22:30:00       NaN       NaN
 ...                       ...       ...
 2021-05-31 21:30:00  0.198487  0.133164
 2021-05-31 22:00:00  0.419132  0.235186
 2021-05-31 22:30:00  0.430699  0.349439
 2021-05-31 23:00:00  0.580911  0.476914
 2021-05-31 23:30:00  0.651560  0.554390

 [65389 rows x 10 columns])

In [24]:
btcusdt.iloc[30000:(30000+1000)]
btcusdt.iloc[0:30000-1].append(btcusdt.iloc[(30000+1000+1):len(btcusdt.index)])

,open time,open,high,low,close,volume,ema,rsi,stoch_k,stoch_d
open time,,,,,,,,,,
2017-08-17 20:30:00,2017-08-17 20:30:00,4301.91,4354.84,4262.53,4346.74,15.184266,4346.740000,NaN,NaN,NaN
2017-08-17 21:00:00,2017-08-17 21:00:00,4346.74,4369.69,4315.85,4349.33,29.292665,4346.765771,100.000000,NaN,NaN
2017-08-17 21:30:00,2017-08-17 21:30:00,4349.33,4369.69,4309.23,4333.55,32.480371,4346.634271,13.225186,NaN,NaN
2017-08-17 22:00:00,2017-08-17 22:00:00,4333.55,4349.63,4310.00,4326.29,26.241174,4346.431840,9.248769,NaN,NaN
2017-08-17 22:30:00,2017-08-17 22:30:00,4326.29,4359.13,4319.11,4336.80,31.134968,4346.336001,38.211911,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2021-05-31 21:30:00,2021-05-31 21:30:00,36775.02,37087.30,36623.01,36932.55,840.717074,36229.710395,58.482794,0.198487,0.133164
2021-05-31 22:00:00,2021-05-31 22:00:00,36932.55,37250.00,36863.28,37090.16,1407.839699,36238.272082,61.498708,0.419132,0.235186
2021-05-31 22:30:00,2021-05-31 22:30:00,37090.16,37140.00,36835.85,36879.23,908.355699,36244.649773,55.670255,0.430699,0.349439
2021-05-31 23:00:00,2021-05-31 23:00:00,36879.23,37345.00,36800.93,37301.51,1160.566735,36255.165795,63.191393,0.580911,0.476914
2021-05-31 23:30:00,2021-05-31 23:30:00,37301.51,37499.00,37231.13,37253.81,1488.587448,36265.102554,61.913553,0.651560,0.554390

In [25]:
len(btcusdt.index)

66391

In [28]:
btcusdt.iloc[len(btcusdt.index)-1]

open time    2021-05-31 23:30:00
open                    37301.51
high                     37499.0
low                     37231.13
close                   37253.81
volume               1488.587448
ema                 36265.102554
rsi                    61.913553
stoch_k                  0.65156
stoch_d                  0.55439
Name: 2021-05-31 23:30:00, dtype: object